Repository vicdsso/AgroconnectFatec, pull requests merged in 2024-06, with the labels that each got.

#20 Perfil e PostCompleto
  src/pages/Perfil/Perfil.jsx
  src/pages/Perfil/Perfil.module.css
  src/pages/PostCompleto/PostCompleto.jsx
Labels: enhancement

#24 adicionando icones na navbar
  package-lock.json
  package.json
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBar.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.css
Labels: enhancement

#26 Refazendo design de login e cadastro
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Cadastro/Cadastro.module.css
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
Labels: enhancement

#30 Adicionando novas funcionalidades
  src/App.jsx
  src/components/Avaliacaouser/Avaform.jsx
  src/components/Avaliacaouser/Avaform.module.css
  src/components/Avaliacaouser/Avalist.jsx
  src/components/Sobre/Sobre.jsx
  src/components/Sobre/Sobre.module.css
  src/pages/Home/Home.jsx
Labels: enhancement

#35 Aprimoramento do Sistema de Notificações - 3 Pontos
  src/App.jsx
  src/components/Notificacao/Notificacao.jsx
  src/components/Notificacao/Notificacao.module.css
  src/pages/Cadastro/Cadastro.jsx
  src/pages/CriarPubli/CriarPubli.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
Labels: enhancement

#36 Adicionar Feedback Visual para Formulários - 3 Pontos
  package-lock.json
  package.json
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Cadastro/Cadastro.module.css
  src/pages/CriarPubli/CriarPubli.jsx
  src/pages/CriarPubli/CriarPubli.module.css
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
Labels: enhancement

#40 Atualização de Componentes Visuais - 3 Pontos
  src/components/Avaliacaouser/Avaform.jsx
  src/components/Publicacoes/Publicacao.module.css
  src/pages/Botaogeral.module.css
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Perfil/Perfil.jsx
Labels: enhancement

#48 criação de testes de componentes
  package-lock.json
  package.json
  src/App.jsx
  src/components/NavbarDashboard/NavbarDashboard.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/UserChart/UserChart.jsx
  src/components/UserTable/UserTable.jsx
  src/pages/DashBoard/DashBoard.jsx
  src/pages/DashBoard/DashBoard.module.css
  src/pages/Home/Home.jsx
  src/testes/BotaTopo/BotaTopo.test.jsx
  src/testes/Noticacao/Noticacao.test.jsx
  src/testes/Publicacao/Publicacao.test.jsx
  src/testes/Sobre/Sobre.test.jsx
Labels: enhancement

#50 Desenvolvimento de testes de performance
  src/App.jsx
  src/testes/BotaTopo/BotaTopo.test.jsx
  src/testes/Publicacao/Publicacao.test.jsx
Labels: documentation

#52 Desenvolvimento de testes de Integração
  src/App.jsx
  src/testes/Noticacao/Notificao.integracao.test.jsx
  src/testes/Publicacao/Publicacao.integracao.test.jsx
Labels: documentation

#54 Desenvolvimento de teste de estress
  package-lock.json
  src/testes/Stress Test/stress-test.yml
  src/testes/Stress Test/stressTest.js
Labels: documentation, enhancement

#55 Dashboard de usuarios
  src/components/UserChart/UserChart.jsx
  src/components/UserTable/UserTable.jsx
  src/pages/DashBoard/DashBoard.jsx
Labels: enhancement

#66 Adicionando novas funcionalidades
  firestore.indexes.json
  firestore.rules
  package-lock.json
  package.json
  public/404.html
  public/index.html
  src/App.jsx
  src/Firebase/AuthContext.jsx
  src/Firebase/Firebaseconfig.jsx
  src/Firebase/ProtectedRoute.jsx
  src/pages/Login/Login.jsx
Labels: enhancement

#67 Implementação de Analytics para Monitoramento de Usuários
  package-lock.json
  package.json
  src/App.jsx
  src/GoogleAnalytics/analytics.js
  src/components/Sobre/Sobre.jsx
Labels: enhancement

#68 Desenvolvimento de Testes de Segurança - 34 Pontos
  package-lock.json
  package.json
  src/testes/Security Tests/security.test.js
Labels: enhancement

#70 Implementação de Modo Escuro - 5 Pontos e Personalização do Tema do S…
  index.html
  package-lock.json
  package.json
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBar.module.css
  src/components/ThemeToggle/ThemeToggle.jsx
  src/contexts/ThemeContext.jsx
Labels: enhancement

#71 Implementação de Painel de Administração com Controle de Acessos
  src/AdminPanel.jsx
  src/App.jsx
  src/Firebase/AuthContext.jsx
Labels: enhancement

#72 Adicionando novas funcionalidades
  package.json
  src/Firebase/backupFirestore.js
Labels: enhancement
